name: Docker Build

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    name: ruby-dev:${{ matrix.ruby }}${{ matrix.variant }}
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 3.4.3
          - 3.4.2
          - 3.3.8
          - 3.3.7
        variant: ["", "-alpine"]
        exclude: []
        include: []
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          visibility: public
          build-args: |
            BASE_IMAGE_TAG=${{ matrix.ruby }}${{ matrix.variant }}

          tags: |
            hnhs/ruby-dev:${{ matrix.ruby }}${{ matrix.variant }}
            ghcr.io/hicknhack-software/ruby-dev:${{ matrix.ruby }}${{ matrix.variant }}

            ${{ matrix.ruby == '3.4.3' && format('hnhs/ruby-dev:latest{0}', matrix.variant) || '' }}
            ${{ matrix.ruby == '3.4.3' && format('ghcr.io/hicknhack-software/ruby-dev:latest{0}', matrix.variant) || '' }}

            ${{ matrix.ruby == '3.4.3' && format('hnhs/ruby-dev:3{0}', matrix.variant) || '' }}
            ${{ matrix.ruby == '3.4.3' && format('ghcr.io/hicknhack-software/ruby-dev:3{0}', matrix.variant) || '' }}

            ${{ matrix.ruby == '3.4.3' && format('hnhs/ruby-dev:3.4{0}', matrix.variant) || '' }}
            ${{ matrix.ruby == '3.4.3' && format('ghcr.io/hicknhack-software/ruby-dev:3.4{0}', matrix.variant) || '' }}

            ${{ matrix.ruby == '3.3.8' && format('hnhs/ruby-dev:3.3{0}', matrix.variant) || '' }}
            ${{ matrix.ruby == '3.3.8' && format('ghcr.io/hicknhack-software/ruby-dev:3.3{0}', matrix.variant) || '' }}

          cache-from: type=gha
          cache-to: type=gha,mode=max
